import "./globals.css";

export const metadata = {
  title: "Vitus | Counselling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return children;
}
