import "./globals.css";

export const metadata = {
  title: "Centre Vitus | Counselling",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return children;
}
